
import java.util.ArrayList;
import java.util.ListIterator;
import javax.swing.JFileChooser;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AskReportWindow.java
 *
 * Created on Jan 11, 2010, 8:53:25 PM
 */

/**
 *
 * @author nikos
 */
public class AskReportWindow extends javax.swing.JFrame {
    /** Creates new form AskReportWindow */

    private LoanManagerController c = new LoanManagerController();
    String strings [] = new String[1000];
    public AskReportWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jAskReportExcludeToFieldTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jAskReportApplyButton = new javax.swing.JButton();
        jAskReportCancelButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jAskReportIncludeFromFieldTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jAskReportIncludeToFieldTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jAskReportExcludeFromFieldTextField = new javax.swing.JTextField();
        jAskReportForComboBox = new javax.swing.JComboBox();
        jAskReportFunctionComboBox = new javax.swing.JComboBox();
        jAskReportCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jAskReportWindowTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAskReportFeatureList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ask Report Window");

        jLabel6.setText("Include Values:");

        jLabel13.setText("To:");

        jLabel12.setText("From:");

        jAskReportApplyButton.setFont(new java.awt.Font("DejaVu Sans", 0, 11));
        jAskReportApplyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accept.png"))); // NOI18N
        jAskReportApplyButton.setText("Apply");
        jAskReportApplyButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jAskReportApplyButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jAskReportApplyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAskReportApplyButtonMouseClicked(evt);
            }
        });

        jAskReportCancelButton.setFont(new java.awt.Font("DejaVu Sans", 0, 11));
        jAskReportCancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel.png"))); // NOI18N
        jAskReportCancelButton.setText("Cancel");
        jAskReportCancelButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jAskReportCancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jAskReportCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAskReportCancelButtonMouseClicked(evt);
            }
        });

        jLabel8.setText("Exclude Values:");

        jLabel10.setText("From:");

        jLabel11.setText("To:");

        jAskReportForComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Loan", "Loaner", "Borrower" }));
        jAskReportForComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAskReportForComboBoxActionPerformed(evt);
            }
        });

        jAskReportFunctionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none", "Average", "Diaspora", "Typiki Apoklisi", " ", " " }));
        jAskReportFunctionComboBox.setEnabled(false);

        jAskReportCheckBox.setText("Save In File");

        jLabel1.setText("Ask Report For:");

        jLabel2.setText("Features:");

        jLabel3.setText("Statistic Infos:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setText("Value:");

        jLabel5.setText("Feature Values:");

        jAskReportFeatureList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Amount", "Rate", "Rate Type", "Risk", "Mortgage Property", "Loan ID", "Loan Type", "Date", "Period", "Sale Value", "Situation" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jAskReportFeatureList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAskReportFeatureListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jAskReportFeatureList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(jAskReportCheckBox))
                        .addComponent(jAskReportForComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(19, 19, 19)
                                .addComponent(jAskReportFunctionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAskReportIncludeFromFieldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAskReportIncludeToFieldTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAskReportExcludeFromFieldTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAskReportExcludeToFieldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAskReportWindowTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAskReportCancelButton)
                        .addGap(18, 18, 18)
                        .addComponent(jAskReportApplyButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jAskReportExcludeFromFieldTextField, jAskReportExcludeToFieldTextField, jAskReportIncludeFromFieldTextField, jAskReportIncludeToFieldTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jAskReportForComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jAskReportFunctionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jAskReportIncludeFromFieldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jAskReportIncludeToFieldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jAskReportExcludeFromFieldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jAskReportExcludeToFieldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel5)
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jAskReportWindowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jAskReportCheckBox)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jAskReportApplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jAskReportCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        pack();
		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
		java.awt.Dimension dialogSize = getSize();
		setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jAskReportApplyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAskReportApplyButtonMouseClicked
        String Value = null, ListValue = null, FunctionValue = null, IncFrom = null, IncTo = null, ExFrom = null, ExTo = null, Txt = null;
        ArrayList<String> QueryResult = new ArrayList<String>();
        String KeyPressed = null, l = null, TmpTxt = null;
        

        int flag = 0, i = 1;
        boolean FileCh;


        FunctionValue = jAskReportFunctionComboBox.getSelectedItem().toString();
        IncFrom = jAskReportIncludeFromFieldTextField.getText();
        IncTo = jAskReportIncludeToFieldTextField.getText();
        ExFrom = jAskReportExcludeFromFieldTextField.getText();
        ExTo = jAskReportExcludeToFieldTextField.getText();
        Txt = jAskReportWindowTextField.getText();
        FileCh = jAskReportCheckBox.isSelected();
        Value=jAskReportForComboBox.getSelectedItem().toString();

       
        if(jAskReportFeatureList.getSelectedValue() == null && jAskReportForComboBox.getSelectedItem().toString() == null && Txt.length()==0) {
            ExceptionWindow d=new ExceptionWindow("Not selected what to ask report for");
            d.setVisible(true);
            return;
        }
        
        else if(jAskReportForComboBox.getSelectedItem().toString() == null && Txt.length() == 0) {
            ExceptionWindow d=new ExceptionWindow("Not selected what to ask report for");
            d.setVisible(true);
            return;
       
        }
        else if (jAskReportFeatureList.getSelectedValue() == null)
        {
            ExceptionWindow d=new ExceptionWindow("Not selected what to ask report for");
            d.setVisible(true);
            return;
        }
        ListValue=jAskReportFeatureList.getSelectedValue().toString();
        System.out.print("ListValue"+ListValue);
        System.out.print("Value"+Value);

   
        if(IncFrom.length()==0 && IncTo.length()==0 && ExFrom.length() == 0 && ExTo.length() == 0 && Txt.length()== 0) {
            Value=jAskReportForComboBox.getSelectedItem().toString();
            QueryResult = c.doViewArchive(Value,null,true);
           
        }    
    
        else{
            Value = jAskReportForComboBox.getSelectedItem().toString();
            ListValue=jAskReportFeatureList.getSelectedValue().toString();
            
            QueryResult = c.doAskReport(Value, ListValue, FunctionValue, IncFrom, IncTo, ExFrom, ExTo, Txt);
        }


        /*Print in file or in so*/
        if (FileCh == true) {
           FileExplorerWindow f = new FileExplorerWindow();
           f.ViewfileSaver(QueryResult, Value, FunctionValue);
        }
        else {
            ViewWindow a = new ViewWindow();
            ListIterator<String> litr = QueryResult.listIterator();
            if (Value.equals("Loaner")) {
                while (litr.hasNext()) {
                  String element = litr.next();
                  if (flag == 1) {
                      i = 1;
                      TmpTxt = null;
                      flag = 0;
                  }
                  if (i <= 4) {
                    if (TmpTxt != null){
                        TmpTxt = TmpTxt + "\t" + element;
                    }
                    else
                       TmpTxt = element;
                       i++;
                    }
                    if (i == 5) {
                       a.copytext(TmpTxt + "\n");
                       flag = 1;
                    }
                }
            }
            else if (Value.equals("Borrower")) {
                if (FunctionValue.equals("Average") || FunctionValue.equals("Dispersion") || FunctionValue.equals("Standard Deviation")) {
                    String element = litr.next();
                    if (FunctionValue.equals("Average"))
                        a.copytext("Average\n");
                    else if (FunctionValue.equals("Dispersion"))
                        a.copytext("Dispersion\n");
                    else
                        a.copytext("Standard Deviation\n");
                    a.copytext("------------------------------------\n");
                    a.copytext(element + "\n");
                }
                else {
                    while (litr.hasNext()) {
                        String element = litr.next();
                        if (flag == 1) {
                            i = 1;
                            TmpTxt = null;
                            flag = 0;
                         }
                        if (i <= 3) {
                            if (TmpTxt != null){
                                TmpTxt = TmpTxt + "\t" + element;
                            }
                            else
                                TmpTxt = element;
                            i++;
                        }
                        if (i == 4) {
                             a.copytext(TmpTxt + "\n");
                             flag = 1;
                         }
                    }
                }
            }
            else {
               if (FunctionValue.equals("Average") || FunctionValue.equals("Dispersion") || FunctionValue.equals("Standard Deviation")) {
                    String element = litr.next();
                    if (FunctionValue.equals("Average"))
                        a.copytext("Average\n");
                    else if (FunctionValue.equals("Dispersion"))
                        a.copytext("Dispersion\n");
                    else
                        a.copytext("Standard Deviation\n");
                    a.copytext("------------------------------------\n");
                    a.copytext(element + "\n");
                }
                else {
                    while (litr.hasNext()) {
                        String element = litr.next();
                        if (flag == 1) {
                            i = 1;
                            TmpTxt = null;
                            flag = 0;
                        }
                        if (i <= 12) {
                            if (TmpTxt != null){
                                TmpTxt = TmpTxt + "\t" + element;
                            }
                            else
                                TmpTxt = element;
                            i++;
                        }
                        if (i == 13) {
                            a.copytext(TmpTxt + "\n");
                            flag = 1;
                        }
                    }
                }
            }
             a.setVisible(true);
    
        }
}//GEN-LAST:event_jAskReportApplyButtonMouseClicked

    private void jAskReportCancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAskReportCancelButtonMouseClicked
        this.setVisible(false);
}//GEN-LAST:event_jAskReportCancelButtonMouseClicked

    private void jAskReportForComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAskReportForComboBoxActionPerformed
        String Item = null;
        
        Item = evt.getActionCommand();
        Item = jAskReportForComboBox.getSelectedItem().toString();
        if(Item.equals("Borrower")) {
            jAskReportFeatureList.setModel(new javax.swing.AbstractListModel() {
                String[] strings = { "ID", "Name", "Risk"};
                public int getSize() { return strings.length; }
                public Object getElementAt(int i) { return strings[i]; }
             });
        }
        else if(Item.equals("Loaner")) {
            jAskReportFeatureList.setModel(new javax.swing.AbstractListModel() {
                String[] strings = { "ID", "Name", "Phone Number", "Contact"};
                public int getSize() { return strings.length; }
                public Object getElementAt(int i) { return strings[i]; }
            });
        }
        else {
            jAskReportFeatureList.setModel(new javax.swing.AbstractListModel() {
                String[] strings = { "Amount", "Rate", "Rate Type", "Risk", "Morgage Property", "Loaner ID", "Loan ID", "Borrower ID", "Loan Type", "Date", "Period", "Sale Value", "Situation", " " };
                public int getSize() { return strings.length; }
                public Object getElementAt(int i) { return strings[i]; }
            });
        }

    }//GEN-LAST:event_jAskReportForComboBoxActionPerformed

    private void jAskReportFeatureListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAskReportFeatureListMouseClicked
        String Value = null, ListValue = null;

        Value = jAskReportForComboBox.getSelectedItem().toString();
        ListValue = jAskReportFeatureList.getSelectedValue().toString();
        if (Value.equals("Loaner")) {
            if (ListValue.equals("Contact") || ListValue.equals("Phone Number") || ListValue.equals("Name")) {
                jAskReportWindowTextField.setEditable(true);
                jAskReportWindowTextField.setText("");
                jAskReportFunctionComboBox.setEnabled(false);
                jAskReportFunctionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none", "Average", "Dispersion", "Standard Deviation" }));
                jAskReportIncludeFromFieldTextField.setEditable(false);
                jAskReportIncludeFromFieldTextField.setText("");
                jAskReportIncludeToFieldTextField.setEditable(false);
                jAskReportIncludeToFieldTextField.setText("");
                jAskReportExcludeFromFieldTextField.setEditable(false);
                jAskReportExcludeFromFieldTextField.setText("");
                jAskReportExcludeToFieldTextField.setEditable(false);
                jAskReportExcludeToFieldTextField.setText("");
            }
            else {
                jAskReportFunctionComboBox.setEnabled(false);
                jAskReportFunctionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none", "Average", "Dispersion", "Standard Deviation" }));
                jAskReportWindowTextField.setEditable(false);
                jAskReportWindowTextField.setText("");
                jAskReportIncludeFromFieldTextField.setEditable(true);
                jAskReportIncludeFromFieldTextField.setText("");
                jAskReportIncludeToFieldTextField.setEditable(true);
                jAskReportIncludeToFieldTextField.setText("");
                jAskReportExcludeFromFieldTextField.setEditable(true);
                jAskReportExcludeFromFieldTextField.setText("");
                jAskReportExcludeToFieldTextField.setEditable(true);
                jAskReportExcludeToFieldTextField.setText("");
            }
        }
        else if (Value.equals("Borrower")) {
           if (ListValue.equals("Name")) {
                jAskReportWindowTextField.setEditable(true);
                jAskReportFunctionComboBox.setEnabled(false);
                jAskReportFunctionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none", "Average", "Dispersion", "Standard Deviation" }));
                jAskReportIncludeFromFieldTextField.setEditable(false);
                jAskReportIncludeFromFieldTextField.setText("");
                jAskReportIncludeToFieldTextField.setEditable(false);
                jAskReportIncludeToFieldTextField.setText("");
                jAskReportExcludeFromFieldTextField.setEditable(false);
                jAskReportExcludeFromFieldTextField.setText("");
                jAskReportExcludeToFieldTextField.setEditable(false);
                jAskReportExcludeToFieldTextField.setText("");
            }
            else {
                jAskReportWindowTextField.setEditable(false);
                jAskReportWindowTextField.setText("");
                if (ListValue.equals("Risk"))
                    jAskReportFunctionComboBox.setEnabled(true);
                else
                    jAskReportFunctionComboBox.setEnabled(false);
                jAskReportFunctionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none", "Average", "Dispersion", "Standard Deviation" }));
                jAskReportIncludeFromFieldTextField.setEditable(true);
                jAskReportIncludeFromFieldTextField.setText("");
                jAskReportIncludeToFieldTextField.setEditable(true);
                jAskReportIncludeToFieldTextField.setText("");
                jAskReportExcludeFromFieldTextField.setEditable(true);
                jAskReportExcludeFromFieldTextField.setText("");
                jAskReportExcludeToFieldTextField.setEditable(true);
                jAskReportExcludeToFieldTextField.setText("");
            }
        }
        else if (Value.equals("Loan")) {
           if (ListValue.equals("Rate Type") || ListValue.equals("Loan Type") || ListValue.equals("Situation") || ListValue.equals("Morgage Property"))  {
                jAskReportWindowTextField.setEditable(true);
                jAskReportWindowTextField.setText("");
                jAskReportFunctionComboBox.setEnabled(false);
                jAskReportFunctionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none", "Average", "Dispersion", "Standard Deviation" }));
                jAskReportIncludeFromFieldTextField.setEditable(false);
                jAskReportIncludeFromFieldTextField.setText("");
                jAskReportIncludeToFieldTextField.setEditable(false);
                jAskReportIncludeToFieldTextField.setText("");
                jAskReportExcludeFromFieldTextField.setEditable(false);
                jAskReportExcludeFromFieldTextField.setText("");
                jAskReportExcludeToFieldTextField.setEditable(false);
                jAskReportExcludeToFieldTextField.setText("");
            }
            else {
                jAskReportWindowTextField.setEditable(false);
                jAskReportWindowTextField.setText("");
                if (ListValue.equals("Amount") || ListValue.equals("Rate") || ListValue.equals("Risk") || ListValue.equals("Sale Value"))
                    jAskReportFunctionComboBox.setEnabled(true);
                else
                    jAskReportFunctionComboBox.setEnabled(false);
                jAskReportFunctionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none", "Average", "Dispersion", "Standard Deviation" }));
                jAskReportIncludeFromFieldTextField.setEditable(true);
                jAskReportIncludeFromFieldTextField.setText("");
                jAskReportIncludeToFieldTextField.setEditable(true);
                jAskReportIncludeToFieldTextField.setText("");
                jAskReportExcludeFromFieldTextField.setEditable(true);
                jAskReportExcludeFromFieldTextField.setText("");
                jAskReportExcludeToFieldTextField.setEditable(true);
                jAskReportExcludeToFieldTextField.setText("");
            }
        }

    }//GEN-LAST:event_jAskReportFeatureListMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AskReportWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAskReportApplyButton;
    private javax.swing.JButton jAskReportCancelButton;
    private javax.swing.JCheckBox jAskReportCheckBox;
    private javax.swing.JTextField jAskReportExcludeFromFieldTextField;
    private javax.swing.JTextField jAskReportExcludeToFieldTextField;
    private javax.swing.JList jAskReportFeatureList;
    private javax.swing.JComboBox jAskReportForComboBox;
    private javax.swing.JComboBox jAskReportFunctionComboBox;
    private javax.swing.JTextField jAskReportIncludeFromFieldTextField;
    private javax.swing.JTextField jAskReportIncludeToFieldTextField;
    private javax.swing.JTextField jAskReportWindowTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
