
import java.lang.NullPointerException;
import java.util.logging.Level;
import java.util.logging.Logger;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MultInputWindow.java
 *
 * Created on Jan 11, 2010, 8:40:15 PM
 */

/**
 *
 * @author nikos
 */
public class MultInputWindow extends javax.swing.JFrame {

    private  LoanManagerController c = new LoanManagerController();
    /** Creates new form MultInputWindow */
    public MultInputWindow() {
        initComponents();
    }
    private boolean Check_If_Arg_Is_Sring(String str)
       {

        //It can't contain only numbers if it's null or empty...

        for (int i = 0; i < str.length(); i++) {

            //If we find a non-digit character we return false.
            if (!Character.isDigit(str.charAt(i)))
                return false;
        }

        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMultinputIDTextField = new javax.swing.JTextField();
        jMultinputNameTextField = new javax.swing.JTextField();
        jMultinputContactTextField = new javax.swing.JTextField();
        jMultinputPhoneTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLoanerLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMultinputSaveButton = new javax.swing.JButton();
        jMultinputClearButton = new javax.swing.JButton();
        jMultinputCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Loaner");

        jMultinputIDTextField.setToolTipText("Loaner's ID");

        jMultinputNameTextField.setToolTipText("Loaner's Name");

        jMultinputContactTextField.setToolTipText("Contact");

        jMultinputPhoneTextField.setToolTipText("Loaner's Phone");

        jLabel4.setText("Name:");

        jLabel7.setText("ID:");

        jLoanerLabel.setText("Add Loaner");
        jLoanerLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLoanerLabel.setIconTextGap(10);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setText("Contact:");

        jLabel9.setText("Phone:");

        jMultinputSaveButton.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jMultinputSaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/save.png"))); // NOI18N
        jMultinputSaveButton.setText("Save");
        jMultinputSaveButton.setToolTipText("Save your Infos");
        jMultinputSaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMultinputSaveButtonMouseClicked(evt);
            }
        });

        jMultinputClearButton.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jMultinputClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/undo.png"))); // NOI18N
        jMultinputClearButton.setText("Clear");
        jMultinputClearButton.setToolTipText("Save your Infos");
        jMultinputClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMultinputClearButtonActionPerformed(evt);
            }
        });

        jMultinputCancelButton.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jMultinputCancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel.png"))); // NOI18N
        jMultinputCancelButton.setText("Cancel");
        jMultinputCancelButton.setToolTipText("Save your Infos");
        jMultinputCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMultinputCancelButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jMultinputPhoneTextField)
                                    .addComponent(jMultinputContactTextField)
                                    .addComponent(jMultinputNameTextField)
                                    .addComponent(jMultinputIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLoanerLabel)
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jMultinputCancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jMultinputClearButton)
                        .addGap(18, 18, 18)
                        .addComponent(jMultinputSaveButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLoanerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jMultinputNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jMultinputIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMultinputContactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMultinputPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMultinputClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMultinputSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMultinputCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
		java.awt.Dimension dialogSize = getSize();
		setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jMultinputSaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMultinputSaveButtonMouseClicked
        // TODO add your handling code here:
        String name = jMultinputNameTextField.getText();
        String id = jMultinputIDTextField.getText();
        String contact = jMultinputContactTextField.getText();
        String phone = jMultinputPhoneTextField.getText();

        ExceptionWindow d;


       //java.lang.

        if(name.length()==0 && id.length()==0 && contact.length() ==0 && phone.length()==0 ){
             d=new ExceptionWindow("No input");
            d.setVisible(true);
            return;

        }
        else if(Check_If_Arg_Is_Sring(id)!=true){
            //this.setVisible(false);
            d=new ExceptionWindow("Field ID must contain only digits");
            d.setVisible(true);
            return;
        }
        else if(Check_If_Arg_Is_Sring(phone)!=true){
            //this.setVisible(false);
            d=new ExceptionWindow("Field phone must contain only digits");
            d.setVisible(true);
            return;
        }
       
        if (!id.equals("")){
            c.doCreateLoaner(id,name,phone,contact);
            this.dispose();
        }

}//GEN-LAST:event_jMultinputSaveButtonMouseClicked

    private void jMultinputCancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMultinputCancelButtonMouseClicked
        //this.setVisible(false);
        this.dispose();
}//GEN-LAST:event_jMultinputCancelButtonMouseClicked

    private void jMultinputClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMultinputClearButtonActionPerformed
        // TODO add your handling code here:
        jMultinputNameTextField.setText("");
        jMultinputIDTextField.setText("");
        jMultinputContactTextField.setText("");
        jMultinputPhoneTextField.setText("");
    }//GEN-LAST:event_jMultinputClearButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultInputWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLoanerLabel;
    private javax.swing.JButton jMultinputCancelButton;
    private javax.swing.JButton jMultinputClearButton;
    private javax.swing.JTextField jMultinputContactTextField;
    private javax.swing.JTextField jMultinputIDTextField;
    private javax.swing.JTextField jMultinputNameTextField;
    private javax.swing.JTextField jMultinputPhoneTextField;
    private javax.swing.JButton jMultinputSaveButton;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables

}
