
import java.util.ArrayList;
import java.util.ListIterator;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OrganiseWindow.java
 *
 * Created on Jan 11, 2010, 8:51:43 PM
 */

/**
 *
 * @author nikos
 */
public class OrganiseWindow extends javax.swing.JFrame {

    private LoanManagerController c = new LoanManagerController();
    /** Creates new form OrganiseWindow */
    public OrganiseWindow() {
        initComponents();
    }

    private void Clean_Table(javax.swing.JTable a){
      int i ,j;
      for(j=0;j<a.getColumnCount();j++)
      {
          for(i=0;i<a.getRowCount();i++)
          {
                 a.setValueAt((String)"",i,j);
          }
      }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jOrganiseApplyButton = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jOrganiseCriteriaList = new javax.swing.JList();
        jOrganiseCancelButton = new javax.swing.JButton();
        jOrganiseIncludeFromFieldTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jOrganiseIncludeToFieldTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jOrganiseExcludeFromFieldTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jOrganiseExcludeToFieldTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jOrganiseWindowTable = new javax.swing.JTable();
        jOrganiseWindowComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Organise Window");
        setResizable(false);

        jLabel6.setText("Include Values:");

        jOrganiseApplyButton.setFont(new java.awt.Font("DejaVu Sans", 0, 11));
        jOrganiseApplyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accept.png"))); // NOI18N
        jOrganiseApplyButton.setText("Apply");
        jOrganiseApplyButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jOrganiseApplyButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jOrganiseApplyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOrganiseApplyButtonMouseClicked(evt);
            }
        });

        jOrganiseCriteriaList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Amount", "Rate", "Date", "Borrower", "Loaner", "Loan Type" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jOrganiseCriteriaList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOrganiseCriteriaListMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jOrganiseCriteriaList);

        jOrganiseCancelButton.setFont(new java.awt.Font("DejaVu Sans", 0, 11));
        jOrganiseCancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel.png"))); // NOI18N
        jOrganiseCancelButton.setText("Cancel");
        jOrganiseCancelButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jOrganiseCancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jOrganiseCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOrganiseCancelButtonMouseClicked(evt);
            }
        });

        jLabel10.setText("From:");

        jLabel11.setText("To:");

        jLabel12.setText("From:");

        jLabel13.setText("To:");

        jLabel7.setText("Organise by:");

        jLabel8.setText("Exclude Values:");

        jOrganiseWindowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Amount", "Rate", "Repayment Date", "Borrower", "Loaner", "Loan Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jOrganiseWindowTable);

        jOrganiseWindowComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Preselected Loans", "Non-Preselected" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jOrganiseIncludeFromFieldTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                            .addComponent(jOrganiseCancelButton, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(6, 6, 6)
                                .addComponent(jOrganiseIncludeToFieldTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                            .addComponent(jOrganiseApplyButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jOrganiseWindowComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 129, Short.MAX_VALUE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jOrganiseExcludeFromFieldTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel13)
                        .addGap(3, 3, 3)
                        .addComponent(jOrganiseExcludeToFieldTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jOrganiseExcludeFromFieldTextField, jOrganiseExcludeToFieldTextField, jOrganiseIncludeFromFieldTextField});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel13});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                        .addGap(32, 32, 32)
                        .addComponent(jOrganiseWindowComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jOrganiseIncludeFromFieldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jOrganiseIncludeToFieldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jOrganiseExcludeFromFieldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jOrganiseExcludeToFieldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jOrganiseCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jOrganiseApplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jOrganiseExcludeFromFieldTextField, jOrganiseExcludeToFieldTextField, jOrganiseIncludeFromFieldTextField, jOrganiseIncludeToFieldTextField});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel13});

        pack();
		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
		java.awt.Dimension dialogSize = getSize();
		setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents



       public void Add_Row(int RowsAlloc) {

        DefaultTableModel model = new DefaultTableModel(
                new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Amount", "Rate", "Repayment Date", "Borrower", "Loaner", "Loan Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        jOrganiseWindowTable.setModel(model);
        for (int k = 0; k < RowsAlloc; k++)
            model.addRow(new Object[][]{null,null,null});
       }





    private void jOrganiseApplyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOrganiseApplyButtonMouseClicked
        // TODO add your handling code here:


        int j,i;
        ExceptionWindow d;
        String IncFrom,IncTo,ExFrom,ExTo,ListValue = null;
        ArrayList<String> QueryResult = new ArrayList<String>();
        IncFrom = jOrganiseIncludeFromFieldTextField.getText();
        IncTo = jOrganiseIncludeToFieldTextField.getText();
        ExFrom = jOrganiseExcludeFromFieldTextField.getText();
        ExTo = jOrganiseExcludeToFieldTextField.getText();
       
        ListValue=(String) jOrganiseCriteriaList.getSelectedValue();

        if(jOrganiseCriteriaList.getSelectedValue()==null)
        {
            /*8a petaksei kai window*/
            d=new ExceptionWindow("No Organise criteria selected");
            d.setVisible(true);
            return;
        }

        String selection = jOrganiseWindowComboBox.getSelectedItem().toString();

        
        if(IncFrom.length()==0 && IncTo.length()==0 && ExFrom.length()==0 && ExTo.length()==0)
        {
             System.out.print("1");
             if(ListValue.equals("Borrower"))
                ListValue = "b_name";
             if(ListValue.equals("Loaner"))
                ListValue = "l_name";
             if(ListValue.equals("Loan Type"))
                ListValue = "l_type";
             if(ListValue.equals("Date"))
                ListValue = "l_date";
            /*8a petaksei kai window*/
             QueryResult = c.doOrganize(ListValue, IncFrom, IncTo,  ExFrom, ExTo, selection);
            
        }
        else
        {
            System.out.print("2");
            QueryResult = c.doOrganize(ListValue, IncFrom, IncTo,  ExFrom, ExTo, selection);
        }

        Clean_Table(jOrganiseWindowTable);

        ListIterator<String> litr = QueryResult.listIterator();

        int RowsAlloc = QueryResult.size()/6 - 2;
         if (QueryResult.size()/6 > 30) {
             Add_Row(RowsAlloc);
         }

        for(j=0; j < QueryResult.size()/6 ; j++)
        {
            for(i=0;i<6;i++)
            {
                String element = litr.next();
                jOrganiseWindowTable.setValueAt((String)element, j,i);
            }
        }

}//GEN-LAST:event_jOrganiseApplyButtonMouseClicked

    private void jOrganiseCancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOrganiseCancelButtonMouseClicked
       this.setVisible(false);
}//GEN-LAST:event_jOrganiseCancelButtonMouseClicked

    private void jOrganiseCriteriaListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOrganiseCriteriaListMouseClicked
        // TODO add your handling code here:
        String organise_choice= (String) jOrganiseCriteriaList.getSelectedValue();
        System.out.print(organise_choice);

        if(organise_choice.equals("Loan Type")){
            jOrganiseIncludeFromFieldTextField.setEditable(false);
            jOrganiseIncludeFromFieldTextField.setText("");
            jOrganiseIncludeToFieldTextField.setEditable(false);
            jOrganiseIncludeToFieldTextField.setText("");
            jOrganiseExcludeFromFieldTextField.setEditable(false);
            jOrganiseExcludeFromFieldTextField.setText("");
            jOrganiseExcludeToFieldTextField.setEditable(false);
            jOrganiseExcludeToFieldTextField.setText("");
        }
        if(organise_choice.equals("Date") ||
                organise_choice.equals("Amount")    ||
                organise_choice.equals("Rate")      ||
                organise_choice.equals("Borrower")  ||
                organise_choice.equals("Loaner"))   {
            jOrganiseIncludeFromFieldTextField.setEditable(true);
            jOrganiseIncludeToFieldTextField.setEditable(true);
            jOrganiseExcludeFromFieldTextField.setEditable(true);
            jOrganiseExcludeToFieldTextField.setEditable(true);

        }

    }//GEN-LAST:event_jOrganiseCriteriaListMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrganiseWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jOrganiseApplyButton;
    private javax.swing.JButton jOrganiseCancelButton;
    private javax.swing.JList jOrganiseCriteriaList;
    private javax.swing.JTextField jOrganiseExcludeFromFieldTextField;
    private javax.swing.JTextField jOrganiseExcludeToFieldTextField;
    private javax.swing.JTextField jOrganiseIncludeFromFieldTextField;
    private javax.swing.JTextField jOrganiseIncludeToFieldTextField;
    private javax.swing.JComboBox jOrganiseWindowComboBox;
    private javax.swing.JTable jOrganiseWindowTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables

}
