/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewWindow.java
 *
 * Created on Jan 11, 2010, 8:55:02 PM
 */

/**
 *
 * @author nikos
 */
public class ViewWindow extends javax.swing.JFrame {

    /** Creates new form ViewWindow */
    public ViewWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jViewWindowCloseButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jViewWindowTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Window");

        jViewWindowCloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accept.png"))); // NOI18N
        jViewWindowCloseButton.setText("Close");
        jViewWindowCloseButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jViewWindowCloseButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jViewWindowCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewWindowCloseButtonActionPerformed(evt);
            }
        });

        jViewWindowTextArea.setColumns(20);
        jViewWindowTextArea.setRows(5);
        jScrollPane1.setViewportView(jViewWindowTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jViewWindowCloseButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jViewWindowCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
		java.awt.Dimension dialogSize = getSize();
		setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jViewWindowCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewWindowCloseButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jViewWindowCloseButtonActionPerformed


    public void copytext(String buf) {
        jViewWindowTextArea.append(buf);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewWindow().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jViewWindowCloseButton;
    private javax.swing.JTextArea jViewWindowTextArea;
    // End of variables declaration//GEN-END:variables

}
