package view;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RemoveLoanerWindow.java
 *
 * Created on Jan 11, 2010, 8:45:12 PM
 */
import LoanManagerController;

import java.util.ArrayList;
import java.util.ListIterator;
//import testmysql.LoanPortfolio;

/**
 * @author   nikos
 */
@SuppressWarnings("serial")
public class RemoveLoanerWindow extends javax.swing.JFrame {

        /**
		 * @uml.property  name="c"
		 * @uml.associationEnd  
		 */
        private  LoanManagerController c = new LoanManagerController();
	String strings [] = new String[1000];

        @SuppressWarnings("unchecked")
		private void fillRLoanerList(){
        int i=1, j=0;
        int flag = 0;
        String TmpTxt = null;

        ArrayList<String> QueryResult = new ArrayList<String>();
        @SuppressWarnings("unused")
		String sql = "SELECT * FROM Loaner";
       
        QueryResult =c.doViewArchive("Loaner",null,true);

        ListIterator<String> litr = QueryResult.listIterator();

        while (litr.hasNext()) {
           String element = litr.next();
           if (flag == 1) {
                   i = 1;
                   TmpTxt = null;
                   flag = 0;
           }
           if (i <= 4) {
                   if (TmpTxt != null){
                           TmpTxt = TmpTxt + "  " + element;
           }
                   else
                           TmpTxt = element;
                   i++;
           }
           if (i == 5) {
                   strings[j] = TmpTxt;
                   flag = 1;
           }
           j++;
        }
    }


    /** Creates new form RemoveLoanerWindow */
    public RemoveLoanerWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRemoveLoanerRemoveButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jRemoveLoanerWindowList = new javax.swing.JList();
        jRemoveLoanerCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remove Loaner Window");

        jRemoveLoanerRemoveButton1.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jRemoveLoanerRemoveButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        jRemoveLoanerRemoveButton1.setText("Remove");
        jRemoveLoanerRemoveButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRemoveLoanerRemoveButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jRemoveLoanerRemoveButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRemoveLoanerRemoveButton1MouseClicked(evt);
            }
        });

	fillRLoanerList();

        jRemoveLoanerWindowList.setModel(new javax.swing.AbstractListModel() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });

        jRemoveLoanerWindowList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRemoveLoanerWindowListFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jRemoveLoanerWindowList);

        jRemoveLoanerCancelButton.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jRemoveLoanerCancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel.png"))); // NOI18N
        jRemoveLoanerCancelButton.setText("Cancel");
        jRemoveLoanerCancelButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRemoveLoanerCancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jRemoveLoanerCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRemoveLoanerCancelButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRemoveLoanerCancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRemoveLoanerRemoveButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRemoveLoanerRemoveButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRemoveLoanerCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
		java.awt.Dimension dialogSize = getSize();
		setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jRemoveLoanerRemoveButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRemoveLoanerRemoveButton1MouseClicked
        // TODO add your handling code here:
        int id = 0;
        String tmp[];

        String ListValue = jRemoveLoanerWindowList.getSelectedValue().toString();
        //System.out.println(ListValue);
        tmp = ListValue.split(" ");
        id = Integer.parseInt(tmp[0]);
        //System.out.println(id);
        
        c.doDeleteLoaner(id);

        for(int i=0; i<1000; i++)
            strings[i]= null;

        fillRLoanerList();
        jRemoveLoanerWindowList.repaint();

}//GEN-LAST:event_jRemoveLoanerRemoveButton1MouseClicked

    private void jRemoveLoanerWindowListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRemoveLoanerWindowListFocusGained
        // TODO add your handling code here:
        
}//GEN-LAST:event_jRemoveLoanerWindowListFocusGained

    private void jRemoveLoanerCancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRemoveLoanerCancelButtonMouseClicked
        //this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jRemoveLoanerCancelButtonMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveLoanerWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jRemoveLoanerCancelButton;
    private javax.swing.JButton jRemoveLoanerRemoveButton1;
    private javax.swing.JList jRemoveLoanerWindowList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
