package view;

import LoanManagerController;

import java.util.ArrayList;
import java.util.ListIterator;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchWindow.java
 *
 * Created on Jan 11, 2010, 8:50:16 PM
 */

/**
 * @author   nikos
 */
@SuppressWarnings("serial")
public class SearchWindow extends javax.swing.JFrame {

    /**
	 * @uml.property  name="c"
	 * @uml.associationEnd  
	 */
    private LoanManagerController c = new LoanManagerController();
    /** Creates new form SearchWindow */
    public SearchWindow() {
        initComponents();
    }

    private void Clean_Table(javax.swing.JTable a){
      int i ,j;
      for(j=0;j<a.getColumnCount();j++)
      {
          for(i=0;i<a.getRowCount();i++)
          {
                 a.setValueAt((String)"",i,j);
          }
      }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jSearchApplyButton = new javax.swing.JButton();
        jSearchCancelButton = new javax.swing.JButton();
        jSearchWindowRateTextField = new javax.swing.JTextField();
        jSearchWindowRepaymentDateTextField = new javax.swing.JTextField();
        jSearchWindowBorrowerTextField = new javax.swing.JTextField();
        jSearchWindowLoanerTextField = new javax.swing.JTextField();
        jSearchWindowLoanTypeTextField = new javax.swing.JTextField();
        jSearchWindowAmountLabel = new javax.swing.JLabel();
        JSearchWindowRateLabel = new javax.swing.JLabel();
        jSearchWindowRepDateLabel = new javax.swing.JLabel();
        jSearchWindowBorrowerLabel = new javax.swing.JLabel();
        jSearchWindowLoanerLabel = new javax.swing.JLabel();
        jSearchWindowLoanTypeLabel = new javax.swing.JLabel();
        jSearchWindowAmountTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSearchWindowTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Window");

        jLabel5.setText("Search by:");

        jSearchApplyButton.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jSearchApplyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accept.png"))); // NOI18N
        jSearchApplyButton.setText("Apply");
        jSearchApplyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSearchApplyButtonMouseClicked(evt);
            }
        });

        jSearchCancelButton.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jSearchCancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel.png"))); // NOI18N
        jSearchCancelButton.setText("Cancel");
        jSearchCancelButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jSearchCancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jSearchCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSearchCancelButtonMouseClicked(evt);
            }
        });

        jSearchWindowRepaymentDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchWindowRepaymentDateTextFieldActionPerformed(evt);
            }
        });

        jSearchWindowAmountLabel.setText("Amount:");

        JSearchWindowRateLabel.setText("Rate:");

        jSearchWindowRepDateLabel.setText("Rep. Date:");

        jSearchWindowBorrowerLabel.setText("Borrower:");

        jSearchWindowLoanerLabel.setText("Loaner:");

        jSearchWindowLoanTypeLabel.setText("Loan Type:");

        jSearchWindowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "LoanID", "Amount", "Rate", "Rate Type", "Date", "Loan Period", "Loan Type", "Sale Value", "Situation", "Loan Risk", "Mortgage Property"
            }
        ) {
            @SuppressWarnings("rawtypes")
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            @SuppressWarnings("rawtypes")
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jSearchWindowTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSearchWindowRepDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSearchWindowBorrowerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSearchWindowLoanerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSearchWindowAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(JSearchWindowRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSearchWindowLoanTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSearchWindowRepaymentDateTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addComponent(jSearchWindowLoanerTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addComponent(jSearchWindowBorrowerTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addComponent(jSearchWindowLoanTypeTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSearchWindowAmountTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addComponent(jSearchWindowRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jSearchCancelButton)
                        .addGap(31, 31, 31)
                        .addComponent(jSearchApplyButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSearchWindowAmountTextField, jSearchWindowBorrowerLabel, jSearchWindowBorrowerTextField, jSearchWindowLoanTypeLabel, jSearchWindowLoanTypeTextField, jSearchWindowLoanerLabel, jSearchWindowLoanerTextField, jSearchWindowRateTextField, jSearchWindowRepDateLabel, jSearchWindowRepaymentDateTextField});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSearchApplyButton, jSearchCancelButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSearchWindowAmountLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JSearchWindowRateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSearchWindowRepDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSearchWindowBorrowerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSearchWindowLoanerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSearchWindowLoanTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSearchWindowAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSearchWindowRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSearchWindowRepaymentDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSearchWindowBorrowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSearchWindowLoanerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSearchWindowLoanTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(236, 236, 236)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSearchCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSearchApplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JSearchWindowRateLabel, jSearchWindowAmountLabel, jSearchWindowAmountTextField, jSearchWindowBorrowerLabel, jSearchWindowBorrowerTextField, jSearchWindowLoanTypeLabel, jSearchWindowLoanTypeTextField, jSearchWindowLoanerLabel, jSearchWindowLoanerTextField, jSearchWindowRateTextField, jSearchWindowRepDateLabel, jSearchWindowRepaymentDateTextField});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jSearchApplyButton, jSearchCancelButton});

        pack();
		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
		java.awt.Dimension dialogSize = getSize();
		setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents


    public void Add_Row(int RowsAlloc) {

        DefaultTableModel model = new DefaultTableModel(new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "LoanID", "Amount", "Rate", "Rate Type", "Date", "Loan Period", "Loan Type", "Sale Value", "Situation", "Loan Risk", "Mortgage Property"})
                {
            @SuppressWarnings("rawtypes")
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            @SuppressWarnings({ "rawtypes", "unchecked" })
			@Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        jSearchWindowTable.setModel(model);
        for (int k = 0; k < RowsAlloc; k++)
            model.addRow(new Object[][]{null,null,null});
       }



    private void jSearchApplyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchApplyButtonMouseClicked
        // TODO add your handling code here:
        @SuppressWarnings("unused")
		int flag = 0,i = 1,j=0;
        
        String Amount=jSearchWindowAmountTextField.getText();
        String Rate=jSearchWindowRateTextField.getText();
        String RepDate=jSearchWindowRepaymentDateTextField.getText();
        String Borrower=jSearchWindowBorrowerTextField.getText();
        String Loaner=jSearchWindowLoanerTextField.getText();
        String LoanType=jSearchWindowLoanTypeTextField.getText();

        
        
        
        Clean_Table(jSearchWindowTable);

       
        if(Amount.length()       ==0   &&
           Rate.length()         ==0   &&
           RepDate.length()      ==0   &&
           Borrower.length()     ==0   &&
           Loaner.length()       ==0   &&
           LoanType.length()     ==0)
        {
            /*8a petaksei kai window*/
            ExceptionWindow d=new ExceptionWindow("NO search criteria selected!");
            d.setVisible(true);
            return;
        }

        
        ArrayList<String> QueryResult = c.doSearch(Amount, Rate, RepDate, Borrower, Loaner, LoanType);
        ListIterator<String> litr = QueryResult.listIterator();

       int RowsAlloc = QueryResult.size()/11 - 2;
         if (QueryResult.size()/11 > 30) {
             Add_Row(RowsAlloc);
         }

        for(j=0; j < QueryResult.size()/11 ; j++)
        {
            for(i=0;i<11;i++)
            {
                String element = litr.next();
                jSearchWindowTable.setValueAt((String)element, j,i);
            }
        }
}//GEN-LAST:event_jSearchApplyButtonMouseClicked

    private void jSearchCancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchCancelButtonMouseClicked
        this.setVisible(false);
}//GEN-LAST:event_jSearchCancelButtonMouseClicked

    private void jSearchWindowRepaymentDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchWindowRepaymentDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchWindowRepaymentDateTextFieldActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JSearchWindowRateLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchApplyButton;
    private javax.swing.JButton jSearchCancelButton;
    private javax.swing.JLabel jSearchWindowAmountLabel;
    private javax.swing.JTextField jSearchWindowAmountTextField;
    private javax.swing.JLabel jSearchWindowBorrowerLabel;
    private javax.swing.JTextField jSearchWindowBorrowerTextField;
    private javax.swing.JLabel jSearchWindowLoanTypeLabel;
    private javax.swing.JTextField jSearchWindowLoanTypeTextField;
    private javax.swing.JLabel jSearchWindowLoanerLabel;
    private javax.swing.JTextField jSearchWindowLoanerTextField;
    private javax.swing.JTextField jSearchWindowRateTextField;
    private javax.swing.JLabel jSearchWindowRepDateLabel;
    private javax.swing.JTextField jSearchWindowRepaymentDateTextField;
    private javax.swing.JTable jSearchWindowTable;
    // End of variables declaration//GEN-END:variables

}
