package view;

import LoanManagerController;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;




/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ValidateChangesWindow.java
 *
 * Created on Jan 19, 2010, 8:34:32 PM
 */

/**
 * @author   argyris
 */
@SuppressWarnings("serial")
public class ValidateChangesWindow extends javax.swing.JFrame {
    /**
	 * @uml.property  name="c"
	 * @uml.associationEnd  
	 */
    private LoanManagerController c = new LoanManagerController();
    private final String a[];
    private final int count;
    @SuppressWarnings("unused")
	private final String text;

   

    /** Creates new form ValidateChangesWindow */
    public ValidateChangesWindow() {
        initComponents();
        this.a=null;
        this.count=0;
        this.text=null;
    }

    public ValidateChangesWindow(String a[],int count,String text){
        initComponents();
        this.a=a;
        this.count = count;
        this.text = text;
        jValidate_ChangesTextArea.append(text);

       
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCancelButton = new javax.swing.JButton();
        jAcceptButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jValidate_ChangesTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel.png"))); // NOI18N
        jCancelButton.setText("Cancel");
        jCancelButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCancelButtonMouseClicked(evt);
            }
        });

        jAcceptButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accept.png"))); // NOI18N
        jAcceptButton.setText("Accept");
        jAcceptButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jAcceptButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jAcceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAcceptButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("Changes To Loan Portfolio:");

        jValidate_ChangesTextArea.setColumns(20);
        jValidate_ChangesTextArea.setEditable(false);
        jValidate_ChangesTextArea.setRows(5);
        jScrollPane1.setViewportView(jValidate_ChangesTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCancelButton)
                        .addGap(18, 18, 18)
                        .addComponent(jAcceptButton))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAcceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
		java.awt.Dimension dialogSize = getSize();
		setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jAcceptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAcceptButtonMouseClicked
        try {
            // TODO add your handling code here:
            
            c.doUpdate(a, count);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(ValidateChangesWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jAcceptButtonMouseClicked

    private void jCancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelButtonMouseClicked
        // TODO add your handling code here:

        ExceptionWindow d=new ExceptionWindow("System Update interrupted by user");
        d.setVisible(true);
        this.setVisible(false);
        return;
    }//GEN-LAST:event_jCancelButtonMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValidateChangesWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAcceptButton;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jValidate_ChangesTextArea;
    // End of variables declaration//GEN-END:variables

}
